# Generated by Django 5.2.5 on 2025-09-10 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
            preserve_default=False,
        ),
    ]
