# Generated by Django 5.2.5 on 2025-10-06 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_profile_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{6}$", "Invalid postal code"
                    )
                ],
            ),
        ),
    ]
