# Generated by Django 5.2.5 on 2026-01-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_user_email_verified_alter_profile_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
