# Generated by Django 5.2.5 on 2026-02-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0005_wallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="use",
            new_name="user",
        ),
    ]
