"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ====================== SECURITY ======================
SECRET_KEY = config('SECRET_KEY', default='django-insecure-temp-key-for-github-actions-collectstatic-only-2026')

DEBUG = config('DEBUG', default=False, cast=bool)

# Azure App Service detection + local fallback
if os.getenv('WEBSITE_HOSTNAME'):
    ALLOWED_HOSTS = [os.getenv('WEBSITE_HOSTNAME')]
    CSRF_TRUSTED_ORIGINS = [f"https://{os.getenv('WEBSITE_HOSTNAME')}"]
else:
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
    CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS',
                                  default='http://localhost:5173,http://127.0.0.1:5173',
                                  cast=Csv())

SITE_URL = config('SITE_URL', default='http://localhost:5173')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ====================== APPLICATION ======================
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_yasg',
    'userauth',
    'store',
    'vendor',
    'customer',
    'addon',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# ====================== DATABASE (defaults for build only) ======================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME', default='dummy_db_for_build'),
        'USER': config('DATABASE_USER', default='dummy_user'),
        'PASSWORD': config('DATABASE_PASSWORD', default='dummy_pass'),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# ====================== PASSWORD VALIDATION ======================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ====================== INTERNATIONALIZATION ======================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# ====================== STATIC & MEDIA ======================
STATIC_URL = 'static/' 
STATICFILES_DIRS = [BASE_DIR / 'static'] 
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = BASE_DIR / 'media'

# Production on Azure App Service → use full absolute URL
if os.getenv('WEBSITE_HOSTNAME'):
    MEDIA_URL = f"https://{os.getenv('WEBSITE_HOSTNAME')}/media/"
else:
    MEDIA_URL = '/media/'


# ====================== CUSTOM ======================
AUTH_USER_MODEL = 'userauth.User'
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='dummy.google.client.id')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================== JAZZMIN ======================
JAZZMIN_SETTINGS = {
    "site_title":"RetroRelics",
    "site_header":"RetroRelics",
    "site_brand" : "RetroRelics",
    "welcome_sign": "Welcome to RetroRelics",
    "copyright" : "Tijo Thomas 2025 All rights reserved",
    'show_ui_builder' :True,
}


# ====================== SIMPLE_JWT ======================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKENS' : True,
    'BLACKLIST_AFTER_ROTATION' :True,
    'UPDATE_LAST_LOGIN' :True
}


# ====================== CORS ======================
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS','PUT', 'PATCH', 'DELETE']
CORS_ALLOW_HEADERS = [
    "X-CSRFToken", "Content-Type", "Authorization", 'accept', 'accept-encoding',
    'authorization', 'content-type', 'dnt', 'origin', 'user-agent', 'x-csrftoken',
    'x-requested-with', 'x-request-id',
]
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True


# ====================== EMAIL ======================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='dummy@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='dummy')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ====================== REST FRAMEWORK ======================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}


# ====================== LOGGING ======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {message}', 'style': '{'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'loggers': {
        'customer': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
}


# ====================== CELERY ======================
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# ====================== RAZORPAY ======================
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='dummy_razorpay_key')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='dummy_razorpay_secret')