# Generated by Django 5.2.5 on 2025-09-10 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid postal code')]),
        ),
    ]
