# Generated by Django 5.2.5 on 2025-10-05 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_cartorder_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="True if cart is unplaced/active; False if converted to order",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{6}$", "Invalid postal code"
                    )
                ],
            ),
        ),
    ]
