# Generated by Django 5.2.5 on 2025-10-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_cart_is_active_alter_cartorder_postal_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartorder",
            old_name="stripe_session_id",
            new_name="razorpay_session_id",
        ),
    ]
