# Generated by Django 5.2.5 on 2025-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_stripe_session_id_cartorder_razorpay_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=1000, null=True
            ),
        ),
    ]
