# Generated by Django 5.2.5 on 2025-12-27 10:32

from django.db import migrations, models

import store.models.product


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_cart_cart_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                default="product.jpg",
                null=True,
                upload_to=store.models.product.product_image_path,
            ),
        ),
    ]
