# Generated by Django 5.2.5 on 2025-12-28 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("change_of_mind", "Change of Mind"),
                            ("wrong_item", "Ordered Wrong Item"),
                            ("found_cheaper", "Found Cheaper Elsewhere"),
                            ("not_needed", "No Longer Needed"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("reason_detail", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                ("is_full_order", models.BooleanField(default=False)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("items", models.ManyToManyField(blank=True, to="store.cartorderitem")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="store.cartorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "Defective/Damaged"),
                            ("wrong_item", "Wrong Item Received"),
                            ("doesnt_fit", "Doesn't Fit"),
                            ("not_as_described", "Not as Described"),
                            ("change_of_mind", "Change of Mind"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("reason_detail", models.TextField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.cartorderitem",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CancelledOrder",
        ),
    ]
