# Generated by Django 5.2.5 on 2026-01-01 06:57

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_ordercancellation_reason_and_more"),
        ("vendor", "0002_alter_vendor_options_vendor_active_vendor_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoffer",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="vendor.vendor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
