# Generated by Django 5.2.5 on 2026-01-01 06:57

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_productoffer_vendor_alter_referraloffer_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
