# Generated by Django 5.2.5 on 2026-01-05 10:32

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_cartorder_coupon_saved_cartorder_offer_saved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="initial_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Total before any discounts (original price + shipping + fees)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="offer_saved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Amount saved from offer discounts",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="saved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Total amount saved",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
