# Generated by Django 5.2.5 on 2026-01-06 14:40

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_cart_initial_total_cart_offer_saved_cart_saved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
