# Generated by Django 5.2.5 on 2026-01-16 13:22

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_referraloffer_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
