# Generated by Django 5.2.5 on 2026-01-16 14:04

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_address_state_alter_referraloffer_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
