# Generated by Django 5.2.5 on 2026-01-16 14:08

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_remove_product_old_price_alter_referraloffer_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
