# Generated by Django 5.2.5 on 2026-01-25 07:51

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_remove_product_old_price_categoryoffer_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "product")},
        ),
    ]
