# Generated by Django 5.2.4 on 2026-02-02 03:41

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_referraloffer_token_alter_review_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreturn",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderreturn",
            name="vendor_response_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("On Hold", "On Hold"),
                    ("Shipping Processing", "Shipping Processing"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Arrived", "Arrived"),
                    ("Delivered", "Delivered"),
                    ("Return Requested", "Return Requested"),
                    ("Returning", "Returning"),
                    ("Returned", "Returned"),
                    ("Cancelled", "Cancelled"),
                ],
                default="On Hold",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orderreturn",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderreturn",
                to="store.cartorderitem",
            ),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
