# Generated by Django 5.2.4 on 2026-02-02 08:45

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Paypal", "Paypal"),
                    ("Credit/Debit Card", "Credit/Debit Card"),
                    ("Wallet Points", "Wallet Points"),
                    ("Wallet", "Wallet"),
                    ("Cash on Delivery", "Cash on Delivery"),
                ],
                help_text="Payment method used for this order",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
