# Generated by Django 5.2.4 on 2026-02-19 15:06

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_add_payment_method_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="oid",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
