# Generated by Django 5.2.4 on 2026-02-27 15:23

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_cartorder_oid_alter_referraloffer_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercancellation",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("pending", "Pending"),
                    ("refunded_to_wallet", "Refunded to Wallet"),
                    ("manually_refunded", "Manually Refunded"),
                ],
                default="not_applicable",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ordercancellation",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="token",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=36, unique=True
            ),
        ),
    ]
